DROP TABLE IF EXISTS book_author;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS publisher;

CREATE TABLE IF NOT EXISTS Author (
	Author_ID SERIAL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Nationality VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Book (
	Book_ID SERIAL PRIMARY KEY,
	Title VARCHAR(100) NOT NULL,
	Genre VARCHAR(50)NOT NULL,
	Publication_Year INTEGER
);




CREATE TABLE IF NOT EXISTS publisher (
	Publisher_ID INTEGER PRIMARY KEY,
	Name VARCHAR(100),
	Country VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS Book_Author (
	id INTEGER PRIMARY KEY,
	AuthorID INTEGER REFERENCES author(Author_ID),
	BookID INTEGER REFERENCES book(Book_ID)
);




